project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Codactics"
  favicon: logo/codactics.ico
  #site-url: https://codactics.github.io/website/
  site-url: "https://www.codactics.com/"
  search: true
  open-graph: true
  twitter-card: true
  page-footer:
    center: "Built by: Codactics, since 2025."
  navbar:
    logo: logo/codactics.png
    background: "#4169e1"
    foreground: "#ffffff"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - href: https://www.facebook.com/Codactics
        icon: facebook
        aria-label: Facebook
      - href: "#"
        icon: github
        aria-label: GitHub
      - href: "https://www.instagram.com/codactics"
        icon: instagram
        aria-label: Instagram

format:
  html:
    include-in-header: plausible.html
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: false
    respect-user-color-scheme: true
